### ISSUE TITLE
Issue with Taking Off

### ISSUE THREAD

**Issue by ClovisTheWriter** [drgmes/doctor-who-mod#11]
I dont know if its a bug, or just something I've done wrong, but after completing the set up using the tutorial video on the main page, every time I tried to take off it just says "The Tardis has already landed", and Im not sure how to fix this if its something I've done wrong, or if its a bug I suppose its on your end to fix.

**Comment by 0ft3n** [comment]
> I dont know if its a bug, or just something I've done wrong, but after completing the set up using the tutorial video on the main page, every time I tried to take off it just says "The Tardis has already landed", and Im not sure how to fix this if its something I've done wrong, or if its a bug I suppose its on your end to fix.

Left click, not right
