### ISSUE TITLE
issues entering the TARDIS crashing the game

### ISSUE THREAD

**Issue by Raidenljk** [drgmes/doctor-who-mod#14]
This happens when I enter the Tardis, basically only when entering and leaving it crashes, but it doesn't corrupt anything it just crashes, I think it must be due to some incompatibility with one of the mods that I have installed, I will pass the last log in case it helps in any way.
[crash-2023-11-30_13.10.37-server.txt](https://github.com/drgmes/doctor-who-mod/files/13516880/crash-2023-11-30_13.10.37-server.txt)
[last log.txt](https://github.com/drgmes/doctor-who-mod/files/13516894/last.log.txt)

**Comment by Cheaterpaul** [comment]
It seems like the doctor who mod makes the player capabilities unavailable.

Same as TeamLapen/Vampirism#1342
