### ISSUE TITLE
Server won't start with DWM installed.

### ISSUE THREAD

**Issue by Hot-M3ss** [drgmes/doctor-who-mod#17]
It launches fine on single player but crashes on a server instance.
[crash-2024-05-13_21.31.50-fml.txt](https://github.com/drgmes/doctor-who-mod/files/15313939/crash-2024-05-13_21.31.50-fml.txt)

**Comment by drgmes** [comment]
@Hot-M3ss Hi! The issue solved in v1.0.10

**Comment by Hot-M3ss** [comment]
Thank you so much! Shocked at how fast you did this.
