### ISSUE TITLE
Possible bug/issue with the teleporter

### ISSUE THREAD

**Issue by Hot-M3ss** [drgmes/doctor-who-mod#18]
https://youtu.be/nUgz0iF6Wjw - I took a video of the bug, not sure if it is one. Ping is excellent and I do not run into the issue but my friend does. Neither the client or the server logs/consoles indicate an issue besides the below, not sure if its related.

21:39:15.312
net.minecraft.client.multiplayer.ClientChunkCache
Render thread
Ignoring chunk since it's not in the view range: 71, 70

[21:42:26] [Server thread/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 100%

**Comment by Hot-M3ss** [comment]
The console also dissapears if you look up

**Comment by drgmes** [comment]
@Hot-M3ss Hi! Unfortunately, I can't reproduce the bug, but i think i found the possible problem and fixed it. Can you check please the version 1.0.11 to make sure the bug is gone?

**Comment by drgmes** [comment]
@Hot-M3ss Regarding the teleport block: this solution was chosen in order not to limit the main console room in where it should begin and end, where the entrances to the generated rooms should be located, etc. Technically, the rooms are generated very far from the console room (minimum 1000 blocks away), so you can replace the console room with another without fear of it affecting your generated rooms. If you have the ImmersivePortals mod installed (which, unfortunately, is only available on Fabric for now), then you won’t even see these teleporter rooms, they will be covered by seamless portals from ImmersivePortals (although physically these rooms will be present behind these portals, you can see this using creative/viewer or simply breaking blocks around)

**Comment by Hot-M3ss** [comment]
I will test this when I can get my friend back on :) thank you. Also that is a completely understandable reason

**Comment by Hot-M3ss** [comment]
@drgmes its fixed! thank you. Are you open to suggestions regarding features?

**Comment by drgmes** [comment]
@Hot-M3ss Yeah, why not, thanks! Please create a new issue with the tag "enhancement", I will be glad to see your suggestions

**Comment by Hot-M3ss** [comment]
Apologies, I forgot my suggestion lol.
