### ISSUE TITLE
Crash with Immersive portal/Synitra connector

### ISSUE THREAD

**Issue by LordMc47** [drgmes/doctor-who-mod#19]
Hi, I'm really looking forward to discovering the rest of the mod, you're really doing a great job. For my part, I found a problem that occurs when using the immersive portal on Forge with Synitra Connector. It works with all other portals, but as soon as you open a tardis, the game crashes as if the portal didn't work. It's quite specific but I had to share it.

**Comment by drgmes** [comment]
@LordMc47 Hi! Issue must be fixed in the new 1.0.12 version
