### ISSUE TITLE
flight start problems

### ISSUE THREAD

**Issue by arturio963** [drgmes/doctor-who-mod#2]
the flight stick does not activate when I repair the tardis or in singleplayer mode or multiplayer mode and the door and the board of the tardis do not activate after repairing I have to leave my world or restart my server for both to activate

**Comment by drgmes** [comment]
@arturio963 hi! Please, try again and when this happens - close the game, open %appdata%/.minecraft/logs (or possibly another minecraft installation path if you are using not official launcher) and send me contents of latest.log file

**Comment by arturio963** [comment]
well and now i activate the flight lever but clicking randomly here is the file 
[latest.log](https://github.com/drgmes/doctor-who-mod/files/12006265/latest.log)
[latest.log](https://github.com/drgmes/doctor-who-mod/files/12006267/latest.log)

**Comment by drgmes** [comment]
@arturio963 Hello again! Problem might be fixed in v1.0.2. If controls does not usable when you log into world after mod updating break the console unit with a pickaxe, put it again on ground and check how all works

**Comment by arturio963** [comment]
I'm sorry but I can't activate the lever, do you want a video as proof?

**Comment by arturio963** [comment]
https://www.mediafire.com/file/akj9rbcv7n90qlh/Minecraft_Forge__1.20.1_-_Singleplayer_2023-07-11_22-06-12.mp4/file

**Comment by arturio963** [comment]
sorry the autor or owner answerme the problem and fix all thnks for your atention also greetings from mexico from this AA guy

**Comment by drgmes** [comment]
@arturio963 Hello again! Seems like the same problem like from this issue: [link](https://github.com/drgmes/doctor-who-mod/issues/3). You must use left mouse button (attack button) on starter stick. I make this point more clear in next update, but it is not technical issue so you can enjoy the game now

**Comment by drgmes** [comment]
@arturio963 Is it works?
