### ISSUE TITLE
Duplicate Keybind options

### ISSUE THREAD

**Issue by danmvision** [drgmes/doctor-who-mod#22]
Hi,
The keybind options are duplicated and if you edit those keybinds it makes the game crash at start with error code 1

key_key.dwm.sonic_device_settings_key:key.keyboard.keypad.0
key_key.dwm.sonic_sunglasses_usage_key:key.keyboard.o
key_key.dwm.sonic_device_settings_key:key.keyboard.keypad.0
key_key.dwm.sonic_sunglasses_usage_key:key.keyboard.o

https://mclo.gs/DdN0qD4
Neoforge 1.21.1
Hopefully its a quick fix.

**Comment by drgmes** [comment]
@danmvision Hi! Could you also provide a list of mods you are running the game with? I suspect it is a compatibility issue

**Comment by danmvision** [comment]
Here's the list but I have a lot...
https://mclo.gs/icKs4yV
I found a "solution" so I can run my main world. I delete the extra lines in the option file before starting my game everytime.

**Comment by drgmes** [comment]
@danmvision Hi again! Thank you for your reply, it helped to identify the problem. In version 1.0.14 there should be no more problems with key bindings, it is ready for download.

(you will need to delete duplicated keys from the options.txt file one last time before using the new version of the mod)

**Comment by danmvision** [comment]
Thanks !! very appreciated
