### ISSUE TITLE
Nether Not Working

### ISSUE THREAD

**Issue by JibberishGulp** [drgmes/doctor-who-mod#4]
I think I've encountered a bit of an actual issue this time. I thought it was just a conflict with my other mods, but even only using the necessary mods for this mod traveling to the nether doesnt work. It will find the nether biome/structure fine and materialise/flight correctly but whenever you go out the door it crashes the game.
[latest nether.txt](https://github.com/drgmes/doctor-who-mod/files/12023651/latest.nether.txt)
[crash-2023-07-12_00.04.49-server.txt](https://github.com/drgmes/doctor-who-mod/files/12023654/crash-2023-07-12_00.04.49-server.txt)

**Comment by drgmes** [comment]
@JibberishGulp Hello again! Problem might be fixed in 1.0.3, you can check it

**Comment by JibberishGulp** [comment]
Hi sorry about the wait, nether loads fine now thank you! One minor issue though, might be more user error, it seems like it is prioritizing spawning on the nether roof instead of the structure itself sometimes. Thank you again for the mod im using it alot so ill be sure to tell you if i run into anything else.
