### ISSUE TITLE
bug architecural server

### ISSUE THREAD

**Issue by laboriens** [drgmes/doctor-who-mod#5]
hello, if you launch the launcher and go to a server without going to a solo world (which has the mod) the list of rooms is empty,

[https://nsm09.casimages.com/img/2023/07/13//23071309201324296018212612.png](url)

to get the list you have to go to a solo world then go to the multi server to see the list

**Comment by drgmes** [comment]
@laboriens Hello! Problem might be fixed in 1.0.4
