### ISSUE TITLE
Cant find a Tardis in my world

### ISSUE THREAD

**Issue by Slipfar** [drgmes/doctor-who-mod#6]
Locate command doesnt seem to work and placing it in from JEI or interacting with a JEI placed tardis crashes the game instantly

**Comment by drgmes** [comment]
@Slipfar Hello! Please, send your crash-report for more information

**Comment by Slipfar** [comment]
Your mod has an incompatibility with valkyrienskies and its physics system if you wanna look into that. However the not finding TARDISes in the world was just me being blind.

**Comment by drgmes** [comment]
@Slipfar Seems like an incompatibility issue with supporting dynamically created dimension. I'm not sure that i can fix this on my side. If the author of that mod adds some API for marking newly dynamically created world to be no handleable by ValkyrienSkies, i could use that and solve the problem.

[ValkyrienSkies2 Issue #501](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/501)
