### ISSUE TITLE
the TARDIS is crasihng the game

### ISSUE THREAD

**Issue by xXshadowWolf** [drgmes/doctor-who-mod#8]
the TARDIS is crasihng the game When i go into it
[crash-2023-07-30_16.30.47-client.txt](https://github.com/drgmes/doctor-who-mod/files/12210403/crash-2023-07-30_16.30.47-client.txt)

**Comment by drgmes** [comment]
@xXshadowWolf Hello! Problem might be fixed in v1.0.7
