### ISSUE TITLE
Entering/exiting the TARDIS causes glitched player state 

### ISSUE THREAD

**Issue by JohnnyProxo** [drgmes/doctor-who-mod#9]
When leaving or entering the TARDIS, the player is put into a glitched state where eating food causes a crash and you lose your Curio items (backpacks, trinkets, ect) as well as your access to things like Mana (Screenshot included) this could have something to do with all my mods but It seems to only happen when I enter/leave the TARDIS through the front door. Teleporting to it via commands or other teleportation traveling does not cause this to happen. The bug fixes itself when traveling to any other dimension.
[crash-2023-08-02_20.44.54-server.txt](https://github.com/drgmes/doctor-who-mod/files/12246678/crash-2023-08-02_20.44.54-server.txt)
![image](https://github.com/drgmes/doctor-who-mod/assets/133610577/6070470b-ef28-4b0e-8a4b-4fde58221774)

**Comment by Test-Account666** [comment]
I have the very same issue.

Except for the crashing when eating food. I don't have SOL installed (Which seems to cause the crash here)

I'm running Mc 1.20.1, Forge 47.1.3.

dwm version 1.0.7

**Comment by jpktz007** [comment]
I also have an issue that seems similar.

dwm version 1.0.7

**Comment by Ashdeuzo** [comment]
same here, any chance for have a fix ?
